// <auto-generated />
using ComponentesTiendaMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComponentesTiendaMVC.Migrations
{
    [DbContext(typeof(OrdenadoresContext))]
    partial class OrdenadoresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponentesTiendaMVC.Models.Componente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Almacenamiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Grados")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrdenadorId")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("TipoComponente")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenadorId");

                    b.ToTable("Componente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Almacenamiento = "0",
                            Cores = 9,
                            Descripcion = "Procesador Intel i7",
                            Grados = 10,
                            NumeroSerie = "789_XCS",
                            OrdenadorId = 1,
                            Precio = 134.0,
                            TipoComponente = 1
                        },
                        new
                        {
                            Id = 2,
                            Almacenamiento = "0",
                            Cores = 10,
                            Descripcion = "Procesador Intel i7",
                            Grados = 12,
                            NumeroSerie = "789_XCD",
                            OrdenadorId = 2,
                            Precio = 138.0,
                            TipoComponente = 1
                        },
                        new
                        {
                            Id = 3,
                            Almacenamiento = "512",
                            Cores = 0,
                            Descripcion = "Banco de memoria SDRAM",
                            Grados = 10,
                            NumeroSerie = "879FH",
                            OrdenadorId = 1,
                            Precio = 100.0,
                            TipoComponente = 2
                        },
                        new
                        {
                            Id = 4,
                            Almacenamiento = "1024",
                            Cores = 0,
                            Descripcion = "Banco de memoria SDRAM",
                            Grados = 15,
                            NumeroSerie = "879FH_L",
                            OrdenadorId = 2,
                            Precio = 125.0,
                            TipoComponente = 2
                        },
                        new
                        {
                            Id = 5,
                            Almacenamiento = "500000",
                            Cores = 0,
                            Descripcion = "Disco Duro Scan Disk",
                            Grados = 10,
                            NumeroSerie = "789_XX",
                            OrdenadorId = 1,
                            Precio = 50.0,
                            TipoComponente = 3
                        },
                        new
                        {
                            Id = 6,
                            Almacenamiento = "1000000",
                            Cores = 0,
                            Descripcion = "Disco Duro Scan Disk",
                            Grados = 29,
                            NumeroSerie = "789_XX_2",
                            OrdenadorId = 2,
                            Precio = 90.0,
                            TipoComponente = 3
                        });
                });

            modelBuilder.Entity("ComponentesTiendaMVC.Models.Ordenador", b =>
                {
                    b.Property<int>("IdOrdenador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrdenador"));

                    b.Property<string>("DescripcionOrdenador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdOrdenador");

                    b.ToTable("Ordenadores");

                    b.HasData(
                        new
                        {
                            IdOrdenador = 1,
                            DescripcionOrdenador = "Almacen"
                        },
                        new
                        {
                            IdOrdenador = 2,
                            DescripcionOrdenador = "Ordenador de Maria"
                        },
                        new
                        {
                            IdOrdenador = 3,
                            DescripcionOrdenador = "Ordenador de Paco"
                        });
                });

            modelBuilder.Entity("ComponentesTiendaMVC.Models.Componente", b =>
                {
                    b.HasOne("ComponentesTiendaMVC.Models.Ordenador", null)
                        .WithMany("Componentes")
                        .HasForeignKey("OrdenadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComponentesTiendaMVC.Models.Ordenador", b =>
                {
                    b.Navigation("Componentes");
                });
#pragma warning restore 612, 618
        }
    }
}
